baseURL: "https://about.wingleung.me/"
title: About Wing Leung
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Know more about Wing Leung, a digital marketing in Hong Kong 
  description: "This is my page made by Hugo, and I am a digital marketing based in Hong Kong with 12 years of experience in website marketing, seo, sem and social media strategy for the Southeast Asia Market."
  keywords: [Digital Marketing, Social Media Marketing, Website Marketing, Blog, Portfolio, PaperMod]
  author: Wing Leung 
  # author: ["Me", "You"] # multiple authors
  images: ["images/wl-icon.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/wl-icon.png"
    favicon16x16: "images/wl-icon.png"
    favicon32x32: "images/wl-icon.png"
    apple_touch_icon: ""
    safari_pinned_tab: ""

  label:
    text: "About Wing Leung"
    icon: "images/wl-icon.png"
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Greetings, this is Wing Leung \U0001F44B"
    subtitle: "A digital marketer with 12 years in the Southeast Asia market, focusing on website marketing and content marketing strategies."
    imageUrl: "images/me.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: About Wing Leung
    buttons:
      - name: "Portfolios"
        url: "/portfolios/"
      - name: "Contact"
        url: mailto:hi@wingleung.me

  # home-info mode
  homeInfoParams:
    Title: "Hello world! \U0001F44B"
    Content: Welcome to my first github page in 2024.

  socialIcons:
    - name: instagram
      url: "https://www.instagram.com/chtwlaa/"
    - name: threads
      url: "https://www.threads.net/@chtwlaa"
    - name: youtube
      url: "https://www.youtube.com/@wingleungsblog2.086"
    - name: linkedin
      url: "https://www.linkedin.com/in/twlaa/"
    - name: github
      url: "https://github.com/twl-dev"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: About
      name: about
      url: /about/
      weight: 10
    - identifier: Portfolios
      name: portfolios
      url: /portfolios/
      weight: 20
    - identifier: blog
      name: blog
      url: https://www.wingleung.me
      weight: 30
    - identifier: search
      name: search
      url: /search/
      weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search
